//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AboutInformation
    {
        public long id { get; set; }
        public Nullable<long> aboutID { get; set; }
        public string informationTitle { get; set; }
        public string informationValue { get; set; }
    
        public virtual About About { get; set; }
    }
}
