//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Blog
    {
        public long id { get; set; }
        public string template { get; set; }
    
        public virtual About About { get; set; }
        public virtual UserInformation UserInformation { get; set; }
        public virtual Contact Contact { get; set; }
        public virtual Home Home { get; set; }
        public virtual Main Main { get; set; }
        public virtual Navigation Navigation { get; set; }
        public virtual Portfolio Portfolio { get; set; }
        public virtual Resume Resume { get; set; }
    }
}
