//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyBlogEntities : DbContext
    {
        public EasyBlogEntities()
            : base("name=EasyBlogEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<About> Abouts { get; set; }
        public virtual DbSet<AboutInformation> AboutInformations { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<HomeSubText> HomeSubTexts { get; set; }
        public virtual DbSet<Main> Mains { get; set; }
        public virtual DbSet<Navigation> Navigations { get; set; }
        public virtual DbSet<NavigationItem> NavigationItems { get; set; }
        public virtual DbSet<Portfolio> Portfolios { get; set; }
        public virtual DbSet<PortfolioCategory> PortfolioCategories { get; set; }
        public virtual DbSet<PortfolioCategoryImageRelationship> PortfolioCategoryImageRelationships { get; set; }
        public virtual DbSet<Resume> Resumes { get; set; }
        public virtual DbSet<ResumeSection> ResumeSections { get; set; }
        public virtual DbSet<ResumeSectionItem> ResumeSectionItems { get; set; }
        public virtual DbSet<ResumeSectionItemExplanation> ResumeSectionItemExplanations { get; set; }
        public virtual DbSet<SocialMedia> SocialMedias { get; set; }
        public virtual DbSet<SocialMediaLink> SocialMediaLinks { get; set; }
        public virtual DbSet<Story> Stories { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<UserInformation> UserInformations { get; set; }
        public virtual DbSet<UserLogin> UserLogins { get; set; }
    }
}
