//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeSubText
    {
        public long id { get; set; }
        public Nullable<long> homeID { get; set; }
        public string subText { get; set; }
    
        public virtual Home Home { get; set; }
    }
}
