//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioCategoryImageRelationship
    {
        public long id { get; set; }
        public Nullable<long> portfolioCategoryID { get; set; }
        public string image { get; set; }
    
        public virtual PortfolioCategory PortfolioCategory { get; set; }
    }
}
