//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortfolioCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PortfolioCategory()
        {
            this.PortfolioCategoryImageRelationships = new HashSet<PortfolioCategoryImageRelationship>();
        }
    
        public long id { get; set; }
        public Nullable<long> portfolioID { get; set; }
        public string category { get; set; }
    
        public virtual Portfolio Portfolio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PortfolioCategoryImageRelationship> PortfolioCategoryImageRelationships { get; set; }
    }
}
